# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_user.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addUserWindow(object):
    def setupUi(self, addUserWindow):
        addUserWindow.setObjectName("addUserWindow")
        addUserWindow.resize(366, 385)
        addUserWindow.setMinimumSize(QtCore.QSize(366, 385))
        addUserWindow.setMaximumSize(QtCore.QSize(366, 385))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addUserWindow.setWindowIcon(icon)
        self.card_number_label = QtWidgets.QLabel(addUserWindow)
        self.card_number_label.setGeometry(QtCore.QRect(19, 28, 71, 16))
        self.card_number_label.setObjectName("card_number_label")
        self.card_number_lineEdit = QtWidgets.QLineEdit(addUserWindow)
        self.card_number_lineEdit.setGeometry(QtCore.QRect(130, 28, 210, 20))
        self.card_number_lineEdit.setText("")
        self.card_number_lineEdit.setMaxLength(28)
        self.card_number_lineEdit.setClearButtonEnabled(True)
        self.card_number_lineEdit.setObjectName("card_number_lineEdit")
        self.first_name_label = QtWidgets.QLabel(addUserWindow)
        self.first_name_label.setGeometry(QtCore.QRect(19, 73, 56, 16))
        self.first_name_label.setObjectName("first_name_label")
        self.first_name_lineEdit = QtWidgets.QLineEdit(addUserWindow)
        self.first_name_lineEdit.setGeometry(QtCore.QRect(130, 73, 210, 20))
        self.first_name_lineEdit.setMaxLength(28)
        self.first_name_lineEdit.setClearButtonEnabled(True)
        self.first_name_lineEdit.setObjectName("first_name_lineEdit")
        self.last_name_label = QtWidgets.QLabel(addUserWindow)
        self.last_name_label.setGeometry(QtCore.QRect(19, 165, 55, 16))
        self.last_name_label.setObjectName("last_name_label")
        self.last_name_lineEdit = QtWidgets.QLineEdit(addUserWindow)
        self.last_name_lineEdit.setGeometry(QtCore.QRect(130, 165, 210, 20))
        self.last_name_lineEdit.setMaxLength(28)
        self.last_name_lineEdit.setClearButtonEnabled(True)
        self.last_name_lineEdit.setObjectName("last_name_lineEdit")
        self.username_label = QtWidgets.QLabel(addUserWindow)
        self.username_label.setGeometry(QtCore.QRect(19, 210, 54, 16))
        self.username_label.setObjectName("username_label")
        self.username_lineEdit = QtWidgets.QLineEdit(addUserWindow)
        self.username_lineEdit.setGeometry(QtCore.QRect(130, 210, 210, 20))
        self.username_lineEdit.setMaxLength(28)
        self.username_lineEdit.setClearButtonEnabled(True)
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.password_label = QtWidgets.QLabel(addUserWindow)
        self.password_label.setGeometry(QtCore.QRect(19, 255, 52, 16))
        self.password_label.setObjectName("password_label")
        self.password_lineEdit = QtWidgets.QLineEdit(addUserWindow)
        self.password_lineEdit.setGeometry(QtCore.QRect(130, 255, 210, 20))
        self.password_lineEdit.setMaxLength(28)
        self.password_lineEdit.setClearButtonEnabled(True)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.email_label = QtWidgets.QLabel(addUserWindow)
        self.email_label.setGeometry(QtCore.QRect(19, 300, 30, 16))
        self.email_label.setObjectName("email_label")
        self.email_lineEdit = QtWidgets.QLineEdit(addUserWindow)
        self.email_lineEdit.setGeometry(QtCore.QRect(130, 300, 210, 20))
        self.email_lineEdit.setMaxLength(28)
        self.email_lineEdit.setClearButtonEnabled(True)
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.ok_cancel_buttonBox = QtWidgets.QDialogButtonBox(addUserWindow)
        self.ok_cancel_buttonBox.setGeometry(QtCore.QRect(130, 350, 211, 23))
        self.ok_cancel_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ok_cancel_buttonBox.setObjectName("ok_cancel_buttonBox")
        self.phone_number_error = QtWidgets.QLineEdit(addUserWindow)
        self.phone_number_error.setGeometry(QtCore.QRect(130, 120, 210, 20))
        self.phone_number_error.setMaxLength(28)
        self.phone_number_error.setClearButtonEnabled(True)
        self.phone_number_error.setObjectName("phone_number_error")
        self.phone_number_label = QtWidgets.QLabel(addUserWindow)
        self.phone_number_label.setGeometry(QtCore.QRect(20, 120, 81, 16))
        self.phone_number_label.setObjectName("phone_number_label")
        self.card_number_error = QtWidgets.QLabel(addUserWindow)
        self.card_number_error.setGeometry(QtCore.QRect(130, 47, 210, 13))
        self.card_number_error.setObjectName("card_number_error")
        self.first_name_error = QtWidgets.QLabel(addUserWindow)
        self.first_name_error.setGeometry(QtCore.QRect(130, 91, 210, 13))
        self.first_name_error.setText("")
        self.first_name_error.setObjectName("first_name_error")
        self.phone_number_error_2 = QtWidgets.QLabel(addUserWindow)
        self.phone_number_error_2.setGeometry(QtCore.QRect(130, 139, 210, 13))
        self.phone_number_error_2.setText("")
        self.phone_number_error_2.setObjectName("phone_number_error_2")
        self.last_name_error = QtWidgets.QLabel(addUserWindow)
        self.last_name_error.setGeometry(QtCore.QRect(130, 185, 210, 13))
        self.last_name_error.setText("")
        self.last_name_error.setObjectName("last_name_error")
        self.username_error = QtWidgets.QLabel(addUserWindow)
        self.username_error.setGeometry(QtCore.QRect(130, 230, 210, 13))
        self.username_error.setText("")
        self.username_error.setObjectName("username_error")
        self.password_error = QtWidgets.QLabel(addUserWindow)
        self.password_error.setGeometry(QtCore.QRect(130, 273, 210, 13))
        self.password_error.setText("")
        self.password_error.setObjectName("password_error")
        self.email_error = QtWidgets.QLabel(addUserWindow)
        self.email_error.setGeometry(QtCore.QRect(130, 320, 210, 13))
        self.email_error.setText("")
        self.email_error.setObjectName("email_error")

        self.retranslateUi(addUserWindow)
        QtCore.QMetaObject.connectSlotsByName(addUserWindow)

    def retranslateUi(self, addUserWindow):
        _translate = QtCore.QCoreApplication.translate
        addUserWindow.setWindowTitle(_translate("addUserWindow", "Student health records "))
        self.card_number_label.setText(_translate("addUserWindow", "Card number*"))
        self.card_number_lineEdit.setPlaceholderText(_translate("addUserWindow", "card number"))
        self.first_name_label.setText(_translate("addUserWindow", "First name*"))
        self.first_name_lineEdit.setPlaceholderText(_translate("addUserWindow", "first name"))
        self.last_name_label.setText(_translate("addUserWindow", "Last name*"))
        self.last_name_lineEdit.setPlaceholderText(_translate("addUserWindow", "last name"))
        self.username_label.setText(_translate("addUserWindow", "Username*"))
        self.username_lineEdit.setPlaceholderText(_translate("addUserWindow", "username"))
        self.password_label.setText(_translate("addUserWindow", "Password*"))
        self.password_lineEdit.setPlaceholderText(_translate("addUserWindow", "password"))
        self.email_label.setText(_translate("addUserWindow", "Email*"))
        self.email_lineEdit.setPlaceholderText(_translate("addUserWindow", "email"))
        self.phone_number_error.setPlaceholderText(_translate("addUserWindow", "phone number"))
        self.phone_number_label.setText(_translate("addUserWindow", "Phone number*"))
        self.card_number_error.setText(_translate("addUserWindow", "<html><head/><body><p><br/></p></body></html>"))

