# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin3.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Student_health_records(object):
    def setupUi(self, Student_health_records):
        Student_health_records.setObjectName("Student_health_records")
        Student_health_records.resize(800, 483)
        Student_health_records.setMinimumSize(QtCore.QSize(800, 483))
        Student_health_records.setMaximumSize(QtCore.QSize(800, 483))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("views/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Student_health_records.setWindowIcon(icon)
        self.save_button = QtWidgets.QPushButton(Student_health_records)
        self.save_button.setGeometry(QtCore.QRect(570, 20, 211, 23))
        self.save_button.setObjectName("save_button")
        self.add_new_button = QtWidgets.QPushButton(Student_health_records)
        self.add_new_button.setGeometry(QtCore.QRect(340, 20, 211, 23))
        self.add_new_button.setObjectName("add_new_button")
        self.name_error = QtWidgets.QLabel(Student_health_records)
        self.name_error.setGeometry(QtCore.QRect(29, 86, 211, 16))
        self.name_error.setObjectName("name_error")
        self.card_number_error = QtWidgets.QLabel(Student_health_records)
        self.card_number_error.setGeometry(QtCore.QRect(29, 136, 211, 16))
        self.card_number_error.setText("")
        self.card_number_error.setObjectName("card_number_error")
        self.group_error = QtWidgets.QLabel(Student_health_records)
        self.group_error.setGeometry(QtCore.QRect(29, 185, 211, 16))
        self.group_error.setText("")
        self.group_error.setObjectName("group_error")
        self.email_error = QtWidgets.QLabel(Student_health_records)
        self.email_error.setGeometry(QtCore.QRect(29, 235, 211, 16))
        self.email_error.setText("")
        self.email_error.setObjectName("email_error")
        self.phone_number_error = QtWidgets.QLabel(Student_health_records)
        self.phone_number_error.setGeometry(QtCore.QRect(29, 286, 211, 16))
        self.phone_number_error.setText("")
        self.phone_number_error.setObjectName("phone_number_error")
        self.full_name_lineEdit = QtWidgets.QLineEdit(Student_health_records)
        self.full_name_lineEdit.setEnabled(True)
        self.full_name_lineEdit.setGeometry(QtCore.QRect(30, 66, 210, 20))
        self.full_name_lineEdit.setInputMask("")
        self.full_name_lineEdit.setMaxLength(30)
        self.full_name_lineEdit.setFrame(True)
        self.full_name_lineEdit.setDragEnabled(False)
        self.full_name_lineEdit.setClearButtonEnabled(True)
        self.full_name_lineEdit.setObjectName("full_name_lineEdit")
        self.card_number_lineEdit = QtWidgets.QLineEdit(Student_health_records)
        self.card_number_lineEdit.setGeometry(QtCore.QRect(30, 117, 210, 20))
        self.card_number_lineEdit.setMaxLength(8)
        self.card_number_lineEdit.setClearButtonEnabled(True)
        self.card_number_lineEdit.setObjectName("card_number_lineEdit")
        self.group_lineEdit = QtWidgets.QLineEdit(Student_health_records)
        self.group_lineEdit.setGeometry(QtCore.QRect(30, 168, 210, 20))
        self.group_lineEdit.setMaxLength(4)
        self.group_lineEdit.setClearButtonEnabled(True)
        self.group_lineEdit.setObjectName("group_lineEdit")
        self.email_lineEdit = QtWidgets.QLineEdit(Student_health_records)
        self.email_lineEdit.setGeometry(QtCore.QRect(30, 219, 210, 20))
        self.email_lineEdit.setMaxLength(30)
        self.email_lineEdit.setClearButtonEnabled(True)
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.phone_number_lineEdit = QtWidgets.QLineEdit(Student_health_records)
        self.phone_number_lineEdit.setGeometry(QtCore.QRect(30, 270, 210, 20))
        self.phone_number_lineEdit.setClearButtonEnabled(True)
        self.phone_number_lineEdit.setObjectName("phone_number_lineEdit")
        self.full_name_label = QtWidgets.QLabel(Student_health_records)
        self.full_name_label.setGeometry(QtCore.QRect(30, 50, 141, 16))
        self.full_name_label.setObjectName("full_name_label")
        self.card_number_label = QtWidgets.QLabel(Student_health_records)
        self.card_number_label.setGeometry(QtCore.QRect(30, 100, 121, 16))
        self.card_number_label.setObjectName("card_number_label")
        self.group_label = QtWidgets.QLabel(Student_health_records)
        self.group_label.setGeometry(QtCore.QRect(30, 150, 131, 16))
        self.group_label.setObjectName("group_label")
        self.email_label = QtWidgets.QLabel(Student_health_records)
        self.email_label.setGeometry(QtCore.QRect(30, 200, 141, 16))
        self.email_label.setObjectName("email_label")
        self.phone_number_label = QtWidgets.QLabel(Student_health_records)
        self.phone_number_label.setGeometry(QtCore.QRect(30, 250, 141, 16))
        self.phone_number_label.setObjectName("phone_number_label")
        self.back_to_info_view_pushButton = QtWidgets.QPushButton(Student_health_records)
        self.back_to_info_view_pushButton.setGeometry(QtCore.QRect(30, 360, 211, 23))
        self.back_to_info_view_pushButton.setObjectName("back_to_info_view_pushButton")
        self.confirm_pushButton = QtWidgets.QPushButton(Student_health_records)
        self.confirm_pushButton.setGeometry(QtCore.QRect(30, 310, 211, 23))
        self.confirm_pushButton.setObjectName("confirm_pushButton")
        self.tableWidget = QtWidgets.QTableWidget(Student_health_records)
        self.tableWidget.setGeometry(QtCore.QRect(340, 90, 431, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(38)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.label = QtWidgets.QLabel(Student_health_records)
        self.label.setGeometry(QtCore.QRect(340, 60, 101, 20))
        self.label.setObjectName("label")

        self.retranslateUi(Student_health_records)
        QtCore.QMetaObject.connectSlotsByName(Student_health_records)

    def retranslateUi(self, Student_health_records):
        _translate = QtCore.QCoreApplication.translate
        Student_health_records.setWindowTitle(_translate("Student_health_records", "Student health records"))
        self.save_button.setText(_translate("Student_health_records", "Save"))
        self.add_new_button.setText(_translate("Student_health_records", "Add new row"))
        self.name_error.setText(_translate("Student_health_records", "<html><head/><body><p><br/></p></body></html>"))
        self.full_name_lineEdit.setText(_translate("Student_health_records", "Rudnyk Taras"))
        self.full_name_lineEdit.setPlaceholderText(_translate("Student_health_records", "Rudnyk Taras "))
        self.card_number_lineEdit.setText(_translate("Student_health_records", "12345678"))
        self.card_number_lineEdit.setPlaceholderText(_translate("Student_health_records", "12345678"))
        self.group_lineEdit.setText(_translate("Student_health_records", "km23"))
        self.group_lineEdit.setPlaceholderText(_translate("Student_health_records", "km23"))
        self.email_lineEdit.setText(_translate("Student_health_records", "tarasrudnyk@gmail.com"))
        self.email_lineEdit.setPlaceholderText(_translate("Student_health_records", "tarasrudnyk@gmail.com"))
        self.phone_number_lineEdit.setInputMask(_translate("Student_health_records", "+38\\0(00)-000-00-00"))
        self.phone_number_lineEdit.setText(_translate("Student_health_records", "+380(95)-465-91-68"))
        self.phone_number_lineEdit.setPlaceholderText(_translate("Student_health_records", "+380954659168"))
        self.full_name_label.setText(_translate("Student_health_records", "Full name"))
        self.card_number_label.setText(_translate("Student_health_records", "Card number"))
        self.group_label.setText(_translate("Student_health_records", "Group"))
        self.email_label.setText(_translate("Student_health_records", "Email"))
        self.phone_number_label.setText(_translate("Student_health_records", "Phone number"))
        self.back_to_info_view_pushButton.setText(_translate("Student_health_records", "Back to information view"))
        self.confirm_pushButton.setText(_translate("Student_health_records", "Confirm"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Student_health_records", "№"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Student_health_records", "Diagnose"))
        self.label.setText(_translate("Student_health_records", "<html><head/><body><p><span style=\" font-size:9pt;\">Diagnoses:</span></p></body></html>"))

