# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin2.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdminShowUsersMenu(object):
    def setupUi(self, AdminShowUsersMenu):
        AdminShowUsersMenu.setObjectName("AdminShowUsersMenu")
        AdminShowUsersMenu.setEnabled(True)
        AdminShowUsersMenu.resize(770, 497)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdminShowUsersMenu.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(AdminShowUsersMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.user_info_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.user_info_tableWidget.setGeometry(QtCore.QRect(30, 30, 711, 421))
        self.user_info_tableWidget.setObjectName("user_info_tableWidget")
        self.user_info_tableWidget.setColumnCount(3)
        self.user_info_tableWidget.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setHorizontalHeaderItem(2, item)
        self.user_info_tableWidget.horizontalHeader().setDefaultSectionSize(235)
        self.Card_number_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Card_number_comboBox.setGeometry(QtCore.QRect(30, 22, 240, 31))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.Card_number_comboBox.setFont(font)
        self.Card_number_comboBox.setEditable(True)
        self.Card_number_comboBox.setMinimumContentsLength(0)
        self.Card_number_comboBox.setObjectName("Card_number_comboBox")
        self.Card_number_comboBox.addItem("")
        self.Card_number_comboBox.setItemText(0, "                           Card number")
        self.Full_name_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Full_name_comboBox.setEnabled(True)
        self.Full_name_comboBox.setGeometry(QtCore.QRect(270, 22, 235, 31))
        self.Full_name_comboBox.setEditable(True)
        self.Full_name_comboBox.setObjectName("Full_name_comboBox")
        self.Full_name_comboBox.addItem("")
        self.Group_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Group_ComboBox.setGeometry(QtCore.QRect(504, 22, 237, 31))
        self.Group_ComboBox.setEditable(True)
        self.Group_ComboBox.setObjectName("Group_ComboBox")
        self.Group_ComboBox.addItem("")
        AdminShowUsersMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdminShowUsersMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setEnabled(False)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        AdminShowUsersMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdminShowUsersMenu)
        self.statusbar.setObjectName("statusbar")
        AdminShowUsersMenu.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(AdminShowUsersMenu)
        self.actionOpen.setEnabled(False)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(AdminShowUsersMenu)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(AdminShowUsersMenu)
        self.actionSave_as.setEnabled(False)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionLog_out = QtWidgets.QAction(AdminShowUsersMenu)
        self.actionLog_out.setObjectName("actionLog_out")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLog_out)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(AdminShowUsersMenu)
        QtCore.QMetaObject.connectSlotsByName(AdminShowUsersMenu)

    def retranslateUi(self, AdminShowUsersMenu):
        _translate = QtCore.QCoreApplication.translate
        AdminShowUsersMenu.setWindowTitle(_translate("AdminShowUsersMenu", "Students health records"))
        self.Card_number_comboBox.setCurrentText(_translate("AdminShowUsersMenu", "                           Card number"))
        self.Full_name_comboBox.setItemText(0, _translate("AdminShowUsersMenu", "                           Full name"))
        self.Group_ComboBox.setItemText(0, _translate("AdminShowUsersMenu", "                              Group"))
        self.menuFile.setTitle(_translate("AdminShowUsersMenu", "File"))
        self.menuHelp.setTitle(_translate("AdminShowUsersMenu", "Help"))
        self.menuAbout.setTitle(_translate("AdminShowUsersMenu", "About"))
        self.actionOpen.setText(_translate("AdminShowUsersMenu", "Open"))
        self.actionSave.setText(_translate("AdminShowUsersMenu", "Save"))
        self.actionSave_as.setText(_translate("AdminShowUsersMenu", "Save as..."))
        self.actionLog_out.setText(_translate("AdminShowUsersMenu", "Log out"))

