# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Student_health_records(object):
    def setupUi(self, Student_health_records):
        Student_health_records.setObjectName("Student_health_records")
        Student_health_records.resize(710, 637)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Student_health_records.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Student_health_records)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.user_info_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.user_info_tableWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_info_tableWidget.sizePolicy().hasHeightForWidth())
        self.user_info_tableWidget.setSizePolicy(sizePolicy)
        self.user_info_tableWidget.setMinimumSize(QtCore.QSize(686, 578))
        self.user_info_tableWidget.setMouseTracking(False)
        self.user_info_tableWidget.setAcceptDrops(False)
        self.user_info_tableWidget.setStatusTip("")
        self.user_info_tableWidget.setWhatsThis("")
        self.user_info_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.user_info_tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_info_tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.user_info_tableWidget.setLineWidth(1)
        self.user_info_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.user_info_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.user_info_tableWidget.setAutoScroll(False)
        self.user_info_tableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.user_info_tableWidget.setShowGrid(True)
        self.user_info_tableWidget.setCornerButtonEnabled(True)
        self.user_info_tableWidget.setRowCount(12)
        self.user_info_tableWidget.setColumnCount(3)
        self.user_info_tableWidget.setObjectName("user_info_tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.user_info_tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_tableWidget.setItem(11, 0, item)
        self.user_info_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.user_info_tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.user_info_tableWidget.horizontalHeader().setMinimumSectionSize(42)
        self.user_info_tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.user_info_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.user_info_tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.user_info_tableWidget.verticalHeader().setDefaultSectionSize(40)
        self.user_info_tableWidget.verticalHeader().setMinimumSectionSize(24)
        self.user_info_tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.user_info_tableWidget.verticalHeader().setStretchLastSection(False)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.user_info_tableWidget)
        Student_health_records.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Student_health_records)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setEnabled(False)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        Student_health_records.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Student_health_records)
        self.statusbar.setObjectName("statusbar")
        Student_health_records.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(Student_health_records)
        self.actionOpen.setEnabled(False)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Student_health_records)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(Student_health_records)
        self.actionSave_as.setEnabled(False)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionLog_out = QtWidgets.QAction(Student_health_records)
        self.actionLog_out.setObjectName("actionLog_out")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionLog_out)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(Student_health_records)
        QtCore.QMetaObject.connectSlotsByName(Student_health_records)

    def retranslateUi(self, Student_health_records):
        _translate = QtCore.QCoreApplication.translate
        Student_health_records.setWindowTitle(_translate("Student_health_records", "Student health records"))
        self.user_info_tableWidget.setSortingEnabled(True)
        item = self.user_info_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Student_health_records", "Diagnose"))
        item = self.user_info_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Student_health_records", "Date"))
        item = self.user_info_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Student_health_records", "Doctor"))
        __sortingEnabled = self.user_info_tableWidget.isSortingEnabled()
        self.user_info_tableWidget.setSortingEnabled(False)
        self.user_info_tableWidget.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("Student_health_records", "File"))
        self.menuHelp.setTitle(_translate("Student_health_records", "Help"))
        self.menuAbout.setTitle(_translate("Student_health_records", "About"))
        self.actionOpen.setText(_translate("Student_health_records", "Open"))
        self.actionSave.setText(_translate("Student_health_records", "Save"))
        self.actionSave_as.setText(_translate("Student_health_records", "Save as..."))
        self.actionLog_out.setText(_translate("Student_health_records", "Log out"))

