# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_user.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(336, 387)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(9, 28, 65, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_medical_card = QtWidgets.QLineEdit(Form)
        self.lineEdit_medical_card.setGeometry(QtCore.QRect(120, 28, 210, 20))
        self.lineEdit_medical_card.setObjectName("lineEdit_medical_card")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(9, 73, 56, 16))
        self.label.setObjectName("label")
        self.lineEdit_first_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_first_name.setGeometry(QtCore.QRect(120, 73, 210, 20))
        self.lineEdit_first_name.setObjectName("lineEdit_first_name")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 55, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_last_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_last_name.setGeometry(QtCore.QRect(120, 165, 210, 20))
        self.lineEdit_last_name.setObjectName("lineEdit_last_name")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(9, 210, 54, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_username = QtWidgets.QLineEdit(Form)
        self.lineEdit_username.setGeometry(QtCore.QRect(120, 210, 210, 20))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(9, 255, 52, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(120, 255, 210, 20))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(9, 300, 30, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_email = QtWidgets.QLineEdit(Form)
        self.lineEdit_email.setGeometry(QtCore.QRect(120, 300, 210, 20))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(150, 350, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit_phone_number = QtWidgets.QLineEdit(Form)
        self.lineEdit_phone_number.setGeometry(QtCore.QRect(120, 120, 210, 20))
        self.lineEdit_phone_number.setObjectName("lineEdit_phone_number")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 165, 81, 16))
        self.label_7.setObjectName("label_7")
        self.medical_card_error = QtWidgets.QLabel(Form)
        self.medical_card_error.setGeometry(QtCore.QRect(120, 47, 210, 13))
        self.medical_card_error.setText("")
        self.medical_card_error.setObjectName("medical_card_error")
        self.fist_name_error = QtWidgets.QLabel(Form)
        self.fist_name_error.setGeometry(QtCore.QRect(120, 91, 210, 13))
        self.fist_name_error.setText("")
        self.fist_name_error.setObjectName("fist_name_error")
        self.last_name_error_2 = QtWidgets.QLabel(Form)
        self.last_name_error_2.setGeometry(QtCore.QRect(120, 139, 210, 13))
        self.last_name_error_2.setText("")
        self.last_name_error_2.setObjectName("last_name_error_2")
        self.phone_number_error = QtWidgets.QLabel(Form)
        self.phone_number_error.setGeometry(QtCore.QRect(120, 185, 210, 13))
        self.phone_number_error.setText("")
        self.phone_number_error.setObjectName("phone_number_error")
        self.user_name_error = QtWidgets.QLabel(Form)
        self.user_name_error.setGeometry(QtCore.QRect(120, 230, 210, 13))
        self.user_name_error.setText("")
        self.user_name_error.setObjectName("user_name_error")
        self.password_error = QtWidgets.QLabel(Form)
        self.password_error.setGeometry(QtCore.QRect(120, 273, 210, 13))
        self.password_error.setText("")
        self.password_error.setObjectName("password_error")
        self.email_error = QtWidgets.QLabel(Form)
        self.email_error.setGeometry(QtCore.QRect(120, 320, 210, 13))
        self.email_error.setText("")
        self.email_error.setObjectName("email_error")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Medical card*"))
        self.label.setText(_translate("Form", "First name*"))
        self.label_2.setText(_translate("Form", "Last name*"))
        self.label_3.setText(_translate("Form", "Username*"))
        self.label_4.setText(_translate("Form", "Password*"))
        self.label_5.setText(_translate("Form", "Email*"))
        self.label_7.setText(_translate("Form", "Phone number*"))

