# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Students_health_records_registration_ui(object):
    def setupUi(self, Students_health_records_registration_ui):
        Students_health_records_registration_ui.setObjectName("Students_health_records_registration_ui")
        Students_health_records_registration_ui.resize(404, 333)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Students_health_records/ui/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Students_health_records_registration_ui.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Students_health_records_registration_ui)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Students_health_records_registration_ui)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_first_name = QtWidgets.QLineEdit(Students_health_records_registration_ui)
        self.lineEdit_first_name.setObjectName("lineEdit_first_name")
        self.gridLayout.addWidget(self.lineEdit_first_name, 0, 1, 1, 2)
        self.First_name_error = QtWidgets.QLabel(Students_health_records_registration_ui)
        self.First_name_error.setText("")
        self.First_name_error.setObjectName("First_name_error")
        self.gridLayout.addWidget(self.First_name_error, 1, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(Students_health_records_registration_ui)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_last_name = QtWidgets.QLineEdit(Students_health_records_registration_ui)
        self.lineEdit_last_name.setObjectName("lineEdit_last_name")
        self.gridLayout.addWidget(self.lineEdit_last_name, 2, 1, 1, 2)
        self.Last_name_error = QtWidgets.QLabel(Students_health_records_registration_ui)
        self.Last_name_error.setText("")
        self.Last_name_error.setObjectName("Last_name_error")
        self.gridLayout.addWidget(self.Last_name_error, 3, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(Students_health_records_registration_ui)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.lineEdit_username = QtWidgets.QLineEdit(Students_health_records_registration_ui)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout.addWidget(self.lineEdit_username, 4, 1, 1, 2)
        self.User_name_error = QtWidgets.QLabel(Students_health_records_registration_ui)
        self.User_name_error.setText("")
        self.User_name_error.setObjectName("User_name_error")
        self.gridLayout.addWidget(self.User_name_error, 5, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(Students_health_records_registration_ui)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(Students_health_records_registration_ui)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout.addWidget(self.lineEdit_password, 6, 1, 1, 2)
        self.Password_error = QtWidgets.QLabel(Students_health_records_registration_ui)
        self.Password_error.setText("")
        self.Password_error.setObjectName("Password_error")
        self.gridLayout.addWidget(self.Password_error, 7, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(Students_health_records_registration_ui)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.lineEdit_Email = QtWidgets.QLineEdit(Students_health_records_registration_ui)
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.gridLayout.addWidget(self.lineEdit_Email, 8, 1, 1, 2)
        self.Emai_error = QtWidgets.QLabel(Students_health_records_registration_ui)
        self.Emai_error.setText("")
        self.Emai_error.setObjectName("Emai_error")
        self.gridLayout.addWidget(self.Emai_error, 9, 1, 1, 2)
        self.sign_up_button = QtWidgets.QPushButton(Students_health_records_registration_ui)
        self.sign_up_button.setObjectName("sign_up_button")
        self.gridLayout.addWidget(self.sign_up_button, 10, 1, 1, 1)
        self.sign_in_button = QtWidgets.QPushButton(Students_health_records_registration_ui)
        self.sign_in_button.setObjectName("sign_in_button")
        self.gridLayout.addWidget(self.sign_in_button, 10, 2, 1, 1)

        self.retranslateUi(Students_health_records_registration_ui)
        QtCore.QMetaObject.connectSlotsByName(Students_health_records_registration_ui)

    def retranslateUi(self, Students_health_records_registration_ui):
        _translate = QtCore.QCoreApplication.translate
        Students_health_records_registration_ui.setWindowTitle(_translate("Students_health_records_registration_ui", "Students_health_records"))
        self.label.setText(_translate("Students_health_records_registration_ui", "First name"))
        self.label_2.setText(_translate("Students_health_records_registration_ui", "Last name"))
        self.label_3.setText(_translate("Students_health_records_registration_ui", "Username*"))
        self.label_4.setText(_translate("Students_health_records_registration_ui", "Password*"))
        self.label_5.setText(_translate("Students_health_records_registration_ui", "Email*"))
        self.sign_up_button.setText(_translate("Students_health_records_registration_ui", "Confirm"))
        self.sign_in_button.setText(_translate("Students_health_records_registration_ui", "Back"))

